### ISSUE TITLE
Typo in 'Manual Inclusion' instructions of ReadMe

### ISSUE THREAD

**Issue by chh51** [mattgallagher/CwlUtils#14]
In step 3 you are referencing 'CwlSignal', even though I don't think CwlSignal is in play yet.  Is this a copy/paste overlook ?

3. Drag the "CwlUtils.framework" from the "Products" folder of the "**CwlSignal**" project to the "Copy Files (Frameworks)" build phases of any target that you want to include this module.

**Comment by mattgallagher** [comment]
Yes, this is a copy and paste error (largely the same instructions are used for CwlUtils and CwlSignal). I've replaced with CwlUtils.
