### ISSUE TITLE
App Store publication issue with Carthage: Framework missing CFBundleVersion

### ISSUE THREAD

**Issue by awall1** [mattgallagher/CwlUtils#22]
When I go to validate my app's IPA for release with Apple, it fails due to an issue it's finding with the Carthage-built version of CwlUtils.

```
"This bundle Payload/My_App.app/Frameworks/CwlUtils.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion. Please find more information about CFBundleVersion at https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleversion"
```

It looks like the Info.plist HAS `CFBundleVersion` set to `$(CURRENT_PROJECT_VERSION)`, which is standard. 

However, `CURRENT_PROJECT_VERSION` is not set in this project's build settings (project.pbxproj). I'm not well versed in setting up Carthage frameworks, but it seems like this current project version should be set. 

I cannot produce a valid build for production with this issue as-is.

**Comment by mattgallagher** [comment]
Hi @awall1, thanks for pointing this out. The "Current Project Setting" (on the Build Settings tab for the project, it is under the Versioning subheading) was missing (I think I accidentally deleted it while tidying up unnecessary project settings).

I've made this change in 6cc52ee822846cfa38e2688cfed1c81164c7e086 on master. With this change, I'm able to submit apps containing CwlUtils.framework to the App Store. If you clear your Cartfile.resolved file and update CwlUtils from master, you'll get this latest change.

**Comment by awall1** [comment]
@mattgallagher Thank you!
