### ISSUE TITLE
README says cocoapods supported

### ISSUE THREAD

**Issue by xaphod** [mattgallagher/CwlUtils#23]
It took me a while to figure out why all of a sudden my pods wouldn't update: your last checkin removed the podspec. 
Not sure why you removed support for Pods, but, it'd be great if you could update the README to mention this -- it still says pods are supported. It'd be even better if you could point out how to "migrate" from pods to swift package manager, or whatever you recommend as a migration path.

**Comment by mattgallagher** [comment]
Sorry about that. I didn't mean to push those changes onto master. I've reorganised the changes onto the xcode11 branch and reverted master to support Cocoapods again.

**Comment by xaphod** [comment]
Ah ok! No worries: thanks very much for the fantastic software you've open-sourced. Really appreciate you.
