### ISSUE TITLE
How to invoke and wait on the main thread?

### ISSUE THREAD

**Issue by reitzig** [mattgallagher/CwlUtils#4]
I've been looking at `Exec` and can not figure out how to `invokeAndWait` from the main thread; none of the cases seems to cover that.

(It's quite confusing that `Exec.mainAsync.invokeAndWait` does not wait.)

**Comment by mattgallagher** [comment]
This is a bug.

Both `main.invokeAndWait` and `mainAsync.invokeAndWait` should have the same behavior: direct invocation if already on the main thread and `Dispatch.main.sync` in all other cases.

I've added some changes to the Exec.main and Exec.mainAsync tests that correctly fail for the previous behavior and correct assert the *fixed* behavior that these should all block and wait for completion.

https://github.com/mattgallagher/CwlUtils/commit/4a16b3d7e5b2dbaae79e3ac6ba848ab72c8b5325
